spring:
  application:
    name: education

  datasource:
    url: jdbc:mysql://localhost:3306/education
    username: root
    password: 1503
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 2040MB
      max-request-size: 2040MB

integration:
  minio:
    access-key: admin
    secret-key: admin@2024
    minio-url: http://localhost:9000

server:
  port: 7000

